{%- set service_name = os.filename.split('.')[0] %}

{%- if not service_name in env.apps %}
  {{ 0/0 }} # Please add this deployment to apps list
{%- endif %}

{%- set app = env.apps[service_name] %}

---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ app.get('namespace', env.k8s.apps.namespace) }}"
